version: '3'
services:
  mysql-db:
    container_name: mysql-db
    env_file:
      - .env
    image: "mysql/mysql-server:5.7" 
    ports:
      - "3307:3306"
    networks:
      mysql-network:
    environment:
      - MYSQL_ONETIME_PASSWORD=true
    volumes:
        - ./data:/var/lib/mysql57:rw
        - ./dbinit:/docker-entrypoint-initdb.d/:ro

  webservice:
    container_name: webservice
    image: webservice:latest
    build: 
      context: Webservice
      dockerfile: Dockerfile
    working_dir: /Webservice
    restart: on-failure
    volumes:
      - ./Webservice:/Webservice
    ports:
      - "8080:8080"
    depends_on: 
      - mysql-db
    networks: 
      mysql-network:
    environment:      
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}    
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db/${MYSQL_DB}?useSSL=false&allowPublicKeyRetrieval=true
    command: mvn clean spring-boot:run
    
networks:
    mysql-network: