FROM maven:3.5-jdk-8
LABEL maintainer="c.richard@etud.univ-pau.fr"
LABEL title="An adapted docker demo of a REST API in Java/Spring using MySQL and Maven"
LABEL GET="You can see all users at http://localhost:8080/api/employees"